### ISSUE TITLE
switchctl from hostname.switch0 fails

### ISSUE THREAD

**Issue by bentley** [vedetta-com/vedetta#125]
From my router:

    starting network
    em0: no link .... got link
    em0: bound to 192.168.0.8 from 192.168.0.1 (XX:XX:XX:XX:XX:XX)
    switchctl: connect: /var/run/switchd.sock: Connection refused

I guess this is because switchd doesn’t start until later in the boot process:

    starting network daemons: sshd switchd dhcpd smtpd sndiod.

Clients work correctly for me if I run switchctl from rc.local instead.

**Comment by h0r14** [comment]
I agree, `switchctl` should not be in `hostname.if`

Do your clients work when connected by crontab?
```console
@reboot      chmod 1777 /tmp; switchctl connect /dev/switch0
```

**Comment by h0r14** [comment]
Connecting to switch from `rc.local` or `crontab` should fix this issue.
Removed `switchctl` from `hostname.switch0` for proper `sh /etc/netstart switch0` reset.

Thank you.
